### ISSUE TITLE
[Feature] 데이터 전처리

### ISSUE THREAD

**Issue by 0unk0** [SesacWannaSIT/WannaSIT#10]
## Description
DB 구축을 위한 데이터 전처리 
- 최종 JSON: preprocessingResult.json

## To-do
- [x] 칸 별 혼잡도, 하차 비율 API 요청 & 응답 저장
- [x] 응답 데이터 가공 -> preprocessingResult.json 생성
- [x] DB 구축

**Comment by Dukkov** [comment]
데이터 전처리 및 DB 서버 구축 완료
